//
//  SettingsInteractor.swift
//  MyCitiesChallenge
//
//  Created by Alejandro isai Acosta Martinez on 08/03/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  The interactor is responsible for managing data from the model layer 
//  (note that Model is not part of the VIPER architecture, feel free to 
//  implement it or not, but for sure it will make our app more concise).
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import Foundation

protocol SettingsBusinessLogic {
    func resetFavorites()
}

final class SettingsInteractor: Interactor, SettingsBusinessLogic {
   
    // MARK: - Properties

    var presenter: SettingsPresentationLogic?
    var router: SettingsRoutingLogic?
    let worker = SettingsWorker()

    // MARK: - Business Logic

    func resetFavorites() {
        CitiesRepository.shared.clearFavorites()
        presenter?.presentResetFavoritesSuccess()
    }

    // MARK: - Routing Logic

}
