//
//  SettingsRouter.swift
//  MyCitiesChallenge
//
//  Created by Alejandro isai Acosta Martinez on 08/03/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This layer is responsible for handling navigation logic: Pushing,
//  Popping, Presenting UIViewControllers.
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import UIKit

protocol SettingsRoutingLogic {
    func routeToSomewhere()
}

final class SettingsRouter: Router, SettingsRoutingLogic {

    weak var view: UIViewController?

    func routeToSomewhere() {
        // Implement navigation logic here
        // Example:
        // let destinationVC = SomeViewController()
        // view?.navigationController?.pushViewController(destinationVC, animated: true)
    }
}
