//
//  FavoritesEntity.swift
//  MyCitiesChallenge
//
//  Created by Alejandro isai Acosta Martinez on 07/03/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Entities are simply our models that the interactor uses through
//  our repository (network layer or data persistence).
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply Clean Architecture to your iOS projects.
//

import Foundation

enum Favorites {
    
    // MARK: - Use cases

    enum SomeUseCase {
        struct Request: Codable {}
        struct Response: Codable {}
        struct ViewModel: Codable {}
    }
}
