//
//  FavoritesRouter.swift
//  MyCitiesChallenge
//
//  Created by Alejandro isai Acosta Martinez on 07/03/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This layer is responsible for handling navigation logic: Pushing,
//  Popping, Presenting UIViewControllers.
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import UIKit

protocol FavoritesRoutingLogic {
    func routeToCityDetail(city: CityList.City)
}

final class FavoritesRouter: Router, FavoritesRoutingLogic {

    weak var view: UIViewController?

    func routeToCityDetail(city: CityList.City) {
        let detailVC = CityDetailViewController(city: city)
        view?.navigationController?.pushViewController(detailVC, animated: true)
    }
}
