//
//  FavoritesInteractor.swift
//  MyCitiesChallenge
//
//  Created by Alejandro isai Acosta Martinez on 07/03/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  The interactor is responsible for managing data from the model layer 
//  (note that Model is not part of the VIPER architecture, feel free to 
//  implement it or not, but for sure it will make our app more concise).
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import Foundation

protocol FavoritesBusinessLogic {
    func fetchFavorites()
    func userInteractionInSomewhere()
}

final class FavoritesInteractor: Interactor, FavoritesBusinessLogic {
   
    // MARK: - Properties

    var presenter: FavoritesPresentationLogic?
    var router: FavoritesRoutingLogic?
    let worker = FavoritesWorker()
    
    private let repository = CitiesRepository.shared

    // MARK: - Business Logic

    func fetchFavorites() {
        let favorites = repository.getFavorites()
        presenter?.presentFavorites(cities: favorites)
    }

    // MARK: - Routing Logic

    func userInteractionInSomewhere() {
        router?.routeToSomewhere()
    }
}
