//
//  CityListWorker.swift
//  MyCitiesChallenge
//
//  Created by Alejandro isai Acosta Martinez on 05/03/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is where we will have direct access to our network layer
//  (APIManager) and our data persistence layer (DataStore). It is important
//  that all the functions in this class always return something.
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply Clean Architecture to your iOS projects.
//

import Foundation

final class CityListWorker {

    func doSomeWork() -> Bool {
        // Example of a simple operation. 
        // This could be a network request, a database fetch, etc.
        return true
    }
}
