//
//  CityListPresenter.swift
//  MyCitiesChallenge
//
//  Created by Alejandro isai Acosta Martinez on 05/03/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  The presenter is the only layer that communicates with the view
//  (The rest of layers communicate with the presenter). Basically,
//  it’s the layer responsible for making decisions based on the
//  user’s actions sent by The View.
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import Foundation

protocol CityListPresentationLogic {
    func presentCities(cities: CityList.LoadCities.Response)
    func presentFilteredCities(cities: CityList.SearchCities.Response)
    func presentFailure(message: String)
}

final class CityListPresenter: Presenter, CityListPresentationLogic {
    
    // MARK: - Properties

    weak var view: CityListDisplayLogic?

    // MARK: - Presentation Logic

    func presentCities(cities: CityList.LoadCities.Response) {
        view?.displayCities(cities: cities)
    }

    func presentFailure(message: String) {
        view?.displayFailure(message: message)
    }
    
    func presentFilteredCities(cities: CityList.SearchCities.Response) {
        view?.displayFilteredCities(cities: cities)
    }
}
